<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * `messenger_messages` (Task 29): the Doctrine transport backing the `async`
 * and `failed` transports in `config/packages/messenger.yaml`.
 *
 * Deferred deliberately from the auth-foundation migration (Task 9's own
 * note): `MESSENGER_TRANSPORT_DSN` carries `auto_setup=0`, so this table
 * never appears on its own, and it could not be diffed until Task 29
 * actually configured a `doctrine://` transport for the schema listener to
 * see. Generated with `doctrine:migrations:diff` against that config,
 * unmodified -- the shape (including the composite index) is
 * `symfony/doctrine-messenger`'s own, not hand-written.
 */
final class Version20260819095142 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'messenger_messages (Task 29): backing table for the async/failed Doctrine Messenger transports.';
    }

    public function up(Schema $schema): void
    {
        $this->addSql(<<<'SQL'
            CREATE TABLE messenger_messages (
              id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
              body TEXT NOT NULL,
              headers TEXT NOT NULL,
              queue_name VARCHAR(190) NOT NULL,
              created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
              available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
              delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
              PRIMARY KEY (id)
            )
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX IDX_75EA56E0FB7336F0E3BD61CE16BA31DBBF396750 ON messenger_messages (
              queue_name, available_at, delivered_at,
              id
            )
        SQL);
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE messenger_messages');
    }
}
